// ===========================================================================
// COUNTRY CONSTANTS
// ===========================================================================

// Country code to full country name mapping
export const COUNTRY_CODE_TO_NAME: Record<string, string> = {
  'US': 'United States',
  'UK': 'United Kingdom',
  'GB': 'United Kingdom',
  'IN': 'India',
  'DE': 'Germany',
  'CA': 'Canada',
  'AU': 'Australia',
  'BR': 'Brazil',
  'FR': 'France',
  'JP': 'Japan',
  'MX': 'Mexico',
  'IT': 'Italy',
  'ES': 'Spain',
  'NL': 'Netherlands',
  'SE': 'Sweden',
  'NO': 'Norway',
  'CH': 'Switzerland',
  'AT': 'Austria',
  'BE': 'Belgium',
  'DK': 'Denmark',
  'FI': 'Finland',
  'PL': 'Poland',
  'CZ': 'Czech Republic',
  'HU': 'Hungary',
  'PT': 'Portugal',
  'GR': 'Greece',
  'IE': 'Ireland',
  'RO': 'Romania',
  'BG': 'Bulgaria',
  'HR': 'Croatia',
  'SI': 'Slovenia',
  'SK': 'Slovakia',
  'LT': 'Lithuania',
  'LV': 'Latvia',
  'EE': 'Estonia',
  'CN': 'China',
  'KR': 'South Korea',
  'SG': 'Singapore',
  'MY': 'Malaysia',
  'TH': 'Thailand',
  'VN': 'Vietnam',
  'ID': 'Indonesia',
  'PH': 'Philippines',
  'TW': 'Taiwan',
  'HK': 'Hong Kong',
  'NZ': 'New Zealand',
  'ZA': 'South Africa',
  'EG': 'Egypt',
  'NG': 'Nigeria',
  'KE': 'Kenya',
  'MA': 'Morocco',
  'AR': 'Argentina',
  'CL': 'Chile',
  'CO': 'Colombia',
  'PE': 'Peru',
  'VE': 'Venezuela',
  'UY': 'Uruguay',
  'EC': 'Ecuador',
  'BO': 'Bolivia',
  'PY': 'Paraguay',
  'IL': 'Israel',
  'AE': 'United Arab Emirates',
  'SA': 'Saudi Arabia',
  'TR': 'Turkey',
  'RU': 'Russia',
  'UA': 'Ukraine',
  'BY': 'Belarus',
  'MD': 'Moldova',
  'AM': 'Armenia',
  'AZ': 'Azerbaijan',
  'GE': 'Georgia',
  'KZ': 'Kazakhstan',
  'UZ': 'Uzbekistan',
  'KG': 'Kyrgyzstan',
  'TJ': 'Tajikistan',
  'TM': 'Turkmenistan',
  'MN': 'Mongolia',
  'BD': 'Bangladesh',
  'PK': 'Pakistan',
  'LK': 'Sri Lanka',
  'MM': 'Myanmar',
  'LA': 'Laos',
  'KH': 'Cambodia',
  'BN': 'Brunei',
  'MV': 'Maldives',
  'BT': 'Bhutan',
  'NP': 'Nepal',
  'AF': 'Afghanistan',
  'IR': 'Iran',
  'IQ': 'Iraq',
  'SY': 'Syria',
  'LB': 'Lebanon',
  'JO': 'Jordan',
  'PS': 'Palestine',
  'CY': 'Cyprus',
  'MT': 'Malta',
  'LU': 'Luxembourg',
  'LI': 'Liechtenstein',
  'AD': 'Andorra',
  'MC': 'Monaco',
  'SM': 'San Marino',
  'VA': 'Vatican City',
  'IS': 'Iceland',
  'FO': 'Faroe Islands',
  'GL': 'Greenland'
}

// Full country names array for data generation (most common countries for analytics)
export const FULL_COUNTRY_NAMES = [
  'United States',
  'India', 
  'Germany',
  'United Kingdom',
  'Canada',
  'Australia',
  'Brazil',
  'France',
  'Japan',
  'Mexico',
  'Italy',
  'Spain',
  'Netherlands',
  'Sweden',
  'Norway',
  'Switzerland',
  'Austria',
  'Belgium',
  'Denmark',
  'Finland',
  'Poland',
  'Czech Republic',
  'Portugal',
  'Greece',
  'Ireland',
  'South Korea',
  'Singapore',
  'Malaysia',
  'Thailand',
  'Indonesia',
  'Philippines',
  'New Zealand',
  'South Africa',
  'Argentina',
  'Chile',
  'Colombia',
  'Israel',
  'United Arab Emirates',
  'Turkey',
  'Russia',
  'China'
]

// Subset of countries for GA4 simulation (10 most common)
export const GA4_SIMULATION_COUNTRIES = [
  'United States', 
  'United Kingdom', 
  'Canada', 
  'Germany', 
  'France', 
  'Australia', 
  'Japan', 
  'India', 
  'Brazil', 
  'Mexico'
]

// Subset for realtime simulation (8 most active)
export const GA4_REALTIME_COUNTRIES = [
  'United States', 
  'United Kingdom', 
  'Canada', 
  'Germany', 
  'France', 
  'Australia', 
  'Japan', 
  'India'
]
